### ISSUE TITLE
Unable to load Win 10 in Banana Pi M64

### ISSUE THREAD

**Issue by rrvenki** [OtakuNekoP/bpi-fel-mass-storage-gui4win#2]
Able to follow the "How to use" until step 4 - Waiting for the FEL loading progress.
In this step few progress bars run in command prompt in PC. Once completed, i see the display screen of Banana PI M64 loading multiple items.  In a last step it says "Loading Kernel..." for about 2 seconds and after that the screen goes black.
I repeated the "how to use" again few times and exactly after "Loading kernel..." message of display from banana pi it crashes.

Any help appreciated.

**Comment by OtakuNekoP** [comment]
The FEL loading progress finished without any error?
After that the screen goes black, could you see the USB Mass Storage Device in your windows Device Manager?
And could you show me your UART0 TTL debug print output of your BPI-M64?

**Comment by rrvenki** [comment]
Hi,
1.	“Unknown Device #1” in the device manager gone as your app was showing the new device detected state.  After clicking "Launch" button there is activity on the 7" display and finally once it reaches "Loading Kernel..." it crashed and black screen appears.
2.    I repeated the same steps again and same "Loading Kernel..." appeared and crashed. After the second time the red LED in the board stopped glowing and the Device Manager in PC stopped detecting the device.  Since then the board appears to be dead.  I'm unable to bring it up.  Looks like it is bricked !!!
3.	i) How to start the board or get it working?
        ii) How do I take the UART0 TTL debug output of BPI-M64?

**Comment by OtakuNekoP** [comment]
Just use the USB-TTL adapter to connect your UART0 on the board with your computer. Then open the terminal (like Putty or XShell) to monitor the COM Port. U'll see the debug message.

**Comment by rrvenki** [comment]
Had customer waiting for the HW + SW as a full solution and did not have luxury to do R&D and wait for solution for a month.  Gave back the device to local supplier and took lattepanda preloaded with Windows 10.  Thanks for your support anyways.
