### ISSUE TITLE
emmc

### ISSUE THREAD

**Issue by 23171580** [OtakuNekoP/bpi-fel-mass-storage-gui4win#3]
https://forum.banana-pi.org.cn/t/topic/2238
你好，我在论坛看到大神写了可以用https://github.com/zador-blood-stained/fel-mass-storage
挂载emmc直接为全志H3的开发板烧录系统到emmc中，我在armbian的https://dl.armbian.com/nanopineo/下载网站，下载了nanopieneo（h3芯片）https://dl.armbian.com/nanopineo/archive/，所有的镜像，用win32diskimager、dd命令、etcher都测试写入了一遍，所有的img镜像写入，重启开发板都无法启动，
U-Boot SPL 2017.11-armbian (Jan 25 2018 - 07:53:42)
DRAM: 512 MiB
Trying to boot from MMC2
MMC Device 1 not found
spl: could not find mmc device. error: -19
SPL: failed to boot from all boot devices
### ERROR ### Please RESET the board ###
都提示上面的错误

**Comment by OtakuNekoP** [comment]
根据我的经验，这个问题和如何烧录没有关系，产生这个问题的原因是在uboot的cmd line中设定的kernel分区路径不对造成的。因为sdcard和emmc都是mmc设备，但是他们的路径是不同的，修改一下root path应该就没有问题了。你要修改的文件在/boot FAT32分区中。

**Comment by Icenowy** [comment]
nano pi neo 似乎没有 emmc。

**Comment by OtakuNekoP** [comment]
没有emmc那就很致命了。

**Comment by 23171580** [comment]
@OtakuNekoP @Icenowy 
yes，手里的板子没有sd卡槽，只有板载的emmc，就是拿nanopineo的测试下，大概知道怎么思路了，
搜到了个关于多设备启动的讨论：https://forum.armbian.com/topic/853-armbian-customization/?page=4#entry8074
继续找方法解决这个问题。
https://forum.armbian.com/topic/2454-fel-mass-storage-or-writing-images-directly-to-emmc/?page=2
原项目的几个armbian开发者讨论着这个问题，然后就没下文了。
