### ISSUE TITLE
M2+

### ISSUE THREAD

**Issue by WeSunniboy** [OtakuNekoP/bpi-fel-mass-storage-gui4win#6]
M2+无法正常使用 M3还是正常

**Comment by OtakuNekoP** [comment]
请问可否提供一下FEL boot时M2+串口输出的dmesg方便确认问题所在？

**Comment by WeSunniboy** [comment]
> 请问可否提供一下FEL boot时M2+串口输出的dmesg方便确认问题所在？

是否可以提供直接的联系方式联系处理.菜鸟刚入门
